/** Regenerate with a separately installed Jison 0.4.18; no runtime generator dependency. */
import { createHash } from "node:crypto";
import { resolve } from "node:path";

const modulePath = process.argv[2];
if (!modulePath) throw new Error("Provide an absolute path to jison 0.4.18's lib/jison.js");
const jison = await import(resolve(modulePath));
if (jison.version !== "0.4.18") throw new Error("Block grammar regeneration requires Jison 0.4.18");
const revision = "97b345154f2cd71f23a2aadb14af6dad46f63173";
const repository = `https://raw.githubusercontent.com/mermaid-js/mermaid/${revision}`;
const [grammar, license] = await Promise.all(
  [
    `${repository}/packages/mermaid/src/diagrams/block/parser/block.jison`,
    `${repository}/LICENSE`,
  ].map(async (url) => {
    const response = await fetch(url);
    if (!response.ok) throw new Error(`${response.status}: ${url}`);
    return response.text();
  }),
);
// Preserve the official lexer and productions; retain earlier chain endpoints.
let nativeGrammar = grammar.replace(
  /(: nodeStatement link node)\s*\{[\s\S]*?\n\s*\}\n(\s*\| node SIZE)/,
  (_, production: string, next: string) =>
    production + " { $$ = yy.linkNodes($1, $2, $3); }\n" + next,
);
if (nativeGrammar === grammar)
  throw new Error("Official link production changed; review its native adapter");
nativeGrammar = nativeGrammar.replaceAll(
  "type: yy.typeStr2Type($1.typeStr), directions: $1.directions",
  "type: yy.typeStr2Type($1.typeStr), typeStr: $1.typeStr, directions: $1.directions",
);
const generated: string = new jison.Parser(nativeGrammar).generate({
  moduleType: "js",
  moduleName: "officialBlockParser",
});
if (/\b(?:eval|require|Function)\s*\(/.test(generated))
  throw new Error("Generated block parser must contain no runtime evaluation or imports");
const header = `// @ts-nocheck — generated parser tables/actions are checked through the typed native adapter.
/* eslint-disable no-unreachable, no-useless-escape, no-unused-vars, no-unused-labels, no-unused-expressions, no-constant-condition, no-control-regex, @typescript-eslint/no-this-alias -- Generated Jison code is preserved. */
/*
 * GENERATED by scripts/generate-block-parser.ts from Mermaid's official block.jison.
 * Upstream revision: ${revision}
 * Grammar SHA-256: ${createHash("sha256").update(grammar).digest("hex")}
 * Native semantic adaptations: recursive links call yy.linkNodes; authored delimiters stay in the AST.
 * The official lexer and grammar productions are unchanged.
 * Generator: Jison 0.4.18. This module has no DOM, runtime evaluation, or dependencies.
 *
${license
  .trim()
  .split("\n")
  .map((line) => " * " + line)
  .join("\n")}
 */
`;
const api = `
export interface BlockGrammarContext {
  getLogger(): { debug(...args: unknown[]): void };
  generateId(): string;
  typeStr2Type(value?: string): string;
  edgeStrToEdgeData(value: string): string;
  edgeStrToEdgeStartData(value: string): string;
  edgeStrToThickness(value: string): string;
  edgeStrToPattern(value: string): string;
  setHierarchy(value: unknown): void;
  linkNodes(from: unknown, link: unknown, to: unknown): unknown[];
  parseError(message: string, hash: { line?: number; loc?: { first_line?: number } }): never;
}
/** The parser owns a fresh state for every call; consumers never touch generated tables. */
export function runOfficialBlockGrammar(source: string, context: BlockGrammarContext): void {
  const parser = new officialBlockParser.Parser();
  parser.yy = context;
  parser.parse(source);
}
`;
const target = resolve(import.meta.dir, "../src/parse/generated/mermaid-block.ts");
await Bun.write(target, header + generated + api);
const formatted = Bun.spawn(["bun", "x", "oxfmt", "--write", target], {
  stdout: "ignore",
  stderr: "inherit",
});
if (await formatted.exited) throw new Error("Generated parser formatting failed");
console.log(`Generated ${target} (${generated.length} parser bytes)`);
